"""
Report generation module.
Renders trading signals into Markdown and plain text formats.
"""
import logging
from datetime import datetime
from typing import Dict, List

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates daily trading reports in Markdown format."""

    def __init__(self, config: Dict):
        self.config = config
        self.timezone = config.get('timezone', 'UTC')

    def generate_markdown(self, signals: Dict, date: str) -> str:
        """
        Generate Markdown report from signals.

        Args:
            signals: Dict with top_equities, top_crypto, all_signals
            date: Report date (YYYY-MM-DD)

        Returns:
            Markdown string
        """
        report = []

        # Header
        report.append(f"# Trading Signals Brief - {date}\n")
        report.append(f"*Generated at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} {self.timezone}*\n")
        report.append("---\n")

        # Executive Summary
        report.append("## Executive Summary\n")
        summary = self._generate_executive_summary(signals)
        for item in summary:
            report.append(f"- {item}")
        report.append("\n---\n")

        # Top Equity Signals
        report.append("## Top Equity Signals\n")
        if signals['top_equities']:
            for i, signal in enumerate(signals['top_equities'], 1):
                report.append(self._format_signal(i, signal))
        else:
            report.append("*No equity signals generated.*\n")
        report.append("\n---\n")

        # Top Crypto Signals
        report.append("## Top Crypto Signals\n")
        if signals['top_crypto']:
            for i, signal in enumerate(signals['top_crypto'], 1):
                report.append(self._format_signal(i, signal))
        else:
            report.append("*No crypto signals generated.*\n")
        report.append("\n---\n")

        # Watchlist Heatmap
        report.append("## Watchlist Heatmap\n")
        report.append(self._generate_heatmap(signals['all_signals']))
        report.append("\n---\n")

        # Caveats & Data Quality
        report.append("## Caveats & Data Quality\n")
        caveats = self._collect_caveats(signals['all_signals'])
        for caveat in caveats:
            report.append(f"- {caveat}")
        report.append("\n---\n")

        # What to Verify Tomorrow
        report.append("## What to Verify Tomorrow\n")
        verification = self._generate_verification_items(signals)
        for item in verification:
            report.append(f"- {item}")
        report.append("\n---\n")

        report.append(f"\n*Report generated by tradz automated system.*\n")

        return "\n".join(report)

    def _generate_executive_summary(self, signals: Dict) -> List[str]:
        """Generate 3-6 bullet points summarizing key findings."""
        summary = []

        all_signals = signals['all_signals']
        if not all_signals:
            return ["No signals generated due to data unavailability."]

        # Market overview
        eq_count = len([s for s in all_signals if s['asset_type'] == 'equity'])
        crypto_count = len([s for s in all_signals if s['asset_type'] == 'crypto'])
        summary.append(f"Analyzed {eq_count} equities and {crypto_count} crypto assets")

        # Top movers
        top_signal = all_signals[0] if all_signals else None
        if top_signal and top_signal['score'] > 70:
            symbol = top_signal['symbol']
            asset_type = top_signal['asset_type']
            score = top_signal['score']
            summary.append(f"Highest signal: {symbol} ({asset_type}) with score {score}/100")

        # Volatility
        high_vol = [s for s in all_signals if s['metrics'].get('volatility_change', 0) > 50]
        if high_vol:
            summary.append(f"{len(high_vol)} assets showing significant volatility spikes (>50%)")

        # Volume
        high_vol_assets = [s for s in all_signals if s['metrics'].get('volume_ratio', 0) > 2.0]
        if high_vol_assets:
            summary.append(f"{len(high_vol_assets)} assets with exceptional volume (>2x average)")

        # Data quality note
        summary.append("Data sourced from yfinance (equities) and ccxt (crypto) - free tier limitations apply")

        return summary[:6]

    def _format_signal(self, rank: int, signal: Dict) -> str:
        """Format a single signal for the report."""
        lines = []

        symbol = signal['symbol']
        score = signal['score']
        metrics = signal['metrics']

        lines.append(f"### {rank}. {symbol} (Score: {score}/100)\n")

        # Key metrics
        lines.append("**Key Metrics:**")
        lines.append(f"- Price: ${metrics.get('last_price', 'N/A')}")
        lines.append(f"- 1-Day Change: {metrics.get('day_return', 0):+.2f}%")
        lines.append(f"- 7-Day Change: {metrics.get('week_return', 0):+.2f}%")
        lines.append(f"- Volatility (7d): {metrics.get('volatility_7d', 0):.1f}%")
        lines.append(f"- Volume Ratio: {metrics.get('volume_ratio', 1):.2f}x\n")

        # Rationale
        lines.append("**Why This Matters:**")
        for reason in signal.get('why', []):
            lines.append(f"- {reason}")
        lines.append("")

        # Caveats (first 2)
        caveats = signal.get('caveats', [])
        if caveats:
            lines.append("**Caveats:**")
            for caveat in caveats[:2]:
                lines.append(f"- {caveat}")
            lines.append("")

        return "\n".join(lines)

    def _generate_heatmap(self, all_signals: List[Dict]) -> str:
        """Generate a table-based heatmap of all watchlist assets."""
        if not all_signals:
            return "*No data available for heatmap.*\n"

        lines = []
        lines.append("| Symbol | Type | 1D % | 7D % | Vol 7d | Volume Ratio | Score |")
        lines.append("|--------|------|------|------|--------|--------------|-------|")

        for signal in all_signals:
            symbol = signal['symbol']
            asset_type = signal['asset_type'][:6]  # Truncate
            metrics = signal['metrics']

            day_ret = metrics.get('day_return', 0)
            week_ret = metrics.get('week_return', 0)
            vol = metrics.get('volatility_7d', 0)
            vol_ratio = metrics.get('volume_ratio', 1)
            score = signal['score']

            lines.append(
                f"| {symbol:<6} | {asset_type:<6} | {day_ret:+.1f}% | {week_ret:+.1f}% | "
                f"{vol:.1f}% | {vol_ratio:.2f}x | {score} |"
            )

        return "\n".join(lines) + "\n"

    def _collect_caveats(self, all_signals: List[Dict]) -> List[str]:
        """Collect unique caveats from all signals."""
        caveats = set()

        for signal in all_signals:
            for caveat in signal.get('caveats', []):
                caveats.add(caveat)

        # Add general caveats
        general_caveats = [
            "Data from free APIs (yfinance/ccxt) may have delays (15-20 minutes for equities)",
            "Crypto data availability depends on exchange uptime and API limits",
            "Historical volatility is not predictive of future volatility",
            "Signal scores are algorithmic and should not be used as sole investment criteria",
            "Always verify signals with additional research before taking action"
        ]

        return general_caveats + list(caveats)

    def _generate_verification_items(self, signals: Dict) -> List[str]:
        """Generate list of items to verify tomorrow."""
        items = []

        # Top signals to monitor
        top_signals = signals['all_signals'][:3]
        if top_signals:
            items.append(
                f"Monitor continuation: {', '.join([s['symbol'] for s in top_signals])}"
            )

        # Volatility spikes
        high_vol = [
            s for s in signals['all_signals']
            if s['metrics'].get('volatility_change', 0) > 50
        ]
        if high_vol:
            items.append(
                f"Check volatility stabilization: {', '.join([s['symbol'] for s in high_vol[:3]])}"
            )

        # Volume anomalies
        high_volume = [
            s for s in signals['all_signals']
            if s['metrics'].get('volume_ratio', 0) > 2.0
        ]
        if high_volume:
            items.append(
                f"Verify volume drivers: {', '.join([s['symbol'] for s in high_volume[:3]])}"
            )

        # General items
        items.append("Review any news or events that may explain today's movements")
        items.append("Update watchlist based on emerging patterns")

        return items[:5]

    def generate_plain_text(self, signals: Dict, date: str) -> str:
        """
        Generate plain text version for email body.

        Args:
            signals: Dict with top_equities, top_crypto, all_signals
            date: Report date (YYYY-MM-DD)

        Returns:
            Plain text string
        """
        # Convert Markdown to simplified plain text
        markdown = self.generate_markdown(signals, date)

        # Simple conversion: remove markdown syntax
        text = markdown.replace('###', '').replace('##', '').replace('**', '')
        text = text.replace('---', '=' * 60)
        text = text.replace('*', '')

        return text
